// <auto-generated />
using System;
using LabFashion.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabFashion.Migrations
{
    [DbContext(typeof(LCCContext))]
    [Migration("20230616213157_ChangeColumnsName")]
    partial class ChangeColumnsName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabFashion.Models.ClothingCollection", b =>
                {
                    b.Property<int>("IdCollection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCollection"));

                    b.Property<string>("BrandCollection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BudgetCollection")
                        .HasColumnType("float");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("LaunchStation")
                        .HasColumnType("int");

                    b.Property<string>("NameCollection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseYearCollection")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("int");

                    b.HasKey("IdCollection");

                    b.HasIndex("IdPerson");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("LabFashion.Models.ModelClothing", b =>
                {
                    b.Property<int>("IdModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModel"));

                    b.Property<int>("IdCollection")
                        .HasColumnType("int");

                    b.Property<int>("LayoutModel")
                        .HasColumnType("int");

                    b.Property<string>("NameModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeModel")
                        .HasColumnType("int");

                    b.HasKey("IdModel");

                    b.HasIndex("IdCollection");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("LabFashion.Models.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"));

                    b.Property<DateTime>("BirthDatePerson")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPerson")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("GenrePerson")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("NamePerson")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumberPerson")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdPerson");

                    b.HasIndex("DocumentPerson")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LabFashion.Models.User", b =>
                {
                    b.HasBaseType("LabFashion.Models.Person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("int");

                    b.Property<int>("TypeUser")
                        .HasColumnType("int");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            BirthDatePerson = new DateTime(1989, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentPerson = "00321456987",
                            GenrePerson = "Masculino",
                            NamePerson = "Renan",
                            PhoneNumberPerson = "12345678900",
                            Email = "renan@email.com",
                            SystemStatus = 1,
                            TypeUser = 1
                        },
                        new
                        {
                            IdPerson = 2,
                            BirthDatePerson = new DateTime(1957, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentPerson = "7564745756",
                            GenrePerson = "Masculino",
                            NamePerson = "José Ricardo",
                            PhoneNumberPerson = "8679678986",
                            Email = "josericardo@email.com",
                            SystemStatus = 2,
                            TypeUser = 1
                        },
                        new
                        {
                            IdPerson = 3,
                            BirthDatePerson = new DateTime(1982, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentPerson = "11111111111",
                            GenrePerson = "Masculino",
                            NamePerson = "Eric",
                            PhoneNumberPerson = "2121121212",
                            Email = "eric@email.com",
                            SystemStatus = 1,
                            TypeUser = 2
                        },
                        new
                        {
                            IdPerson = 4,
                            BirthDatePerson = new DateTime(1991, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentPerson = "43124321432",
                            GenrePerson = "Feminino",
                            NamePerson = "Priscila",
                            PhoneNumberPerson = "52345432543",
                            Email = "priscila@email.com",
                            SystemStatus = 2,
                            TypeUser = 1
                        },
                        new
                        {
                            IdPerson = 5,
                            BirthDatePerson = new DateTime(1953, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentPerson = "86973535445",
                            GenrePerson = "Feminino",
                            NamePerson = "Sonia",
                            PhoneNumberPerson = "0978096463",
                            Email = "sonia@email.com",
                            SystemStatus = 1,
                            TypeUser = 3
                        });
                });

            modelBuilder.Entity("LabFashion.Models.ClothingCollection", b =>
                {
                    b.HasOne("LabFashion.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LabFashion.Models.ModelClothing", b =>
                {
                    b.HasOne("LabFashion.Models.ClothingCollection", "ClothingCollection")
                        .WithMany()
                        .HasForeignKey("IdCollection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClothingCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
